# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_SSII.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import PelisSimilares as ps

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget) # Boton Ranking
        self.pushButton.setGeometry(QtCore.QRect(710, 530, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button_clicked)

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget) # Text edit 
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 221, 31))
        self.textEdit.setObjectName("textEdit")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget) # Boton Informacion
        self.pushButton_2.setGeometry(QtCore.QRect(620, 530, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget) # Text Area
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 80, 771, 391))
        self.plainTextEdit.setObjectName("plainTextEdit")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Ranking"))
        self.pushButton_2.setText(_translate("MainWindow", "Informacion"))

    def button_clicked(self):
        film = self.textEdit.toPlainText()
        ranking = ps.genre_recommendations(film, ps.cosine_sim_df, ps.movies[['title', 'genres']])
        self.plainTextEdit.setPlainText(str(ranking))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())