# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_SSII.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import Recomendador_general as rg
import Predicciones_usuario as pu
import WebScraping as ws

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.tabWidget.setObjectName("tabWidget")

        # Tab General, Objetivo 1
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.plainTxtGeneral = QtWidgets.QPlainTextEdit(self.tabGeneral)
        self.plainTxtGeneral.setGeometry(QtCore.QRect(10, 80, 771, 391))
        self.plainTxtGeneral.setObjectName("plainTxtGeneral")
        self.plainTxtGeneral.setReadOnly(True)
        self.txtEditGeneral = QtWidgets.QTextEdit(self.tabGeneral)
        self.txtEditGeneral.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.txtEditGeneral.setObjectName("txtEditGeneral")
        self.btnRanking = QtWidgets.QPushButton(self.tabGeneral)
        self.btnRanking.setGeometry(QtCore.QRect(710, 520, 75, 23))
        self.btnRanking.setObjectName("btnRanking")
        self.btnRanking.clicked.connect(self.btnRanking_clicked)
        self.label_3 = QtWidgets.QLabel(self.tabGeneral)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 200, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lblErrorGeneral = QtWidgets.QLabel(self.tabGeneral)
        self.lblErrorGeneral.setGeometry(QtCore.QRect(250, 30, 250, 30))
        self.lblErrorGeneral.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.lblErrorGeneral.setText("")
        self.lblErrorGeneral.setObjectName("lblErrorGeneral")
        self.tabWidget.addTab(self.tabGeneral, "")

        # Tab Usuario, Objetivo 2
        self.tabUser = QtWidgets.QWidget()
        self.tabUser.setObjectName("tabUser")
        self.txtEditUser = QtWidgets.QTextEdit(self.tabUser)
        self.txtEditUser.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.txtEditUser.setObjectName("txtEditUser")
        self.plainTxtUser = QtWidgets.QPlainTextEdit(self.tabUser)
        self.plainTxtUser.setGeometry(QtCore.QRect(10, 80, 771, 391))
        self.plainTxtUser.setObjectName("plainTxtUser")
        self.plainTxtUser.setReadOnly(True)
        self.btnPredict = QtWidgets.QPushButton(self.tabUser)
        self.btnPredict.setGeometry(QtCore.QRect(710, 520, 75, 23))
        self.btnPredict.setObjectName("btnPredict")
        self.btnPredict.clicked.connect(self.btnPredict_clicked)
        self.btnRankingUser = QtWidgets.QPushButton(self.tabUser)
        self.btnRankingUser.setGeometry(QtCore.QRect(620, 520, 75, 23))
        self.btnRankingUser.setObjectName("btnRankingUser")
        self.btnRankingUser.clicked.connect(self.btnRankingUser_clicked)
        self.label_2 = QtWidgets.QLabel(self.tabUser)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 200, 16))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lblErrorUser = QtWidgets.QLabel(self.tabUser)
        self.lblErrorUser.setGeometry(QtCore.QRect(250, 30, 250, 30))
        self.lblErrorUser.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.lblErrorUser.setText("")
        self.lblErrorUser.setObjectName("lblErrorUser")
        self.tabWidget.addTab(self.tabUser, "")

        # Tab Informacion, WebScraping
        self.tabInformacion = QtWidgets.QWidget()
        self.tabInformacion.setObjectName("tabInformacion")
        self.plainTxtInfo = QtWidgets.QPlainTextEdit(self.tabInformacion)
        self.plainTxtInfo.setGeometry(QtCore.QRect(10, 150, 771, 321))
        self.plainTxtInfo.setObjectName("plainTxtInfo")
        self.txtEditInfo = QtWidgets.QTextEdit(self.tabInformacion)
        self.txtEditInfo.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.txtEditInfo.setObjectName("txtEditInfo")
        self.label = QtWidgets.QLabel(self.tabInformacion)
        self.label.setGeometry(QtCore.QRect(10, 10, 200, 16))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lblGenres = QtWidgets.QLabel(self.tabInformacion)
        self.lblGenres.setGeometry(QtCore.QRect(0, 80, 771, 41))
        self.lblGenres.setText("")
        self.lblGenres.setObjectName("lblGenres")
        self.btnInformation = QtWidgets.QPushButton(self.tabInformacion)
        self.btnInformation.setGeometry(QtCore.QRect(710, 530, 75, 23))
        self.btnInformation.setObjectName("btnInformation")
        self.btnInformation.clicked.connect(self.btnInformation_clicked)
        self.lblErrorInfo = QtWidgets.QLabel(self.tabInformacion)
        self.lblErrorInfo.setGeometry(QtCore.QRect(250, 30, 250, 30))
        self.lblErrorInfo.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.lblErrorInfo.setText("")
        self.lblErrorInfo.setObjectName("lblErrorInfo")
        self.tabWidget.addTab(self.tabInformacion, "")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistemas Inteligentes"))
        self.btnRanking.setText(_translate("MainWindow", "Ranking"))
        self.label_3.setText(_translate("MainWindow", "Introduzca la pelicula"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("MainWindow", "Recomendador General"))
        self.btnPredict.setText(_translate("MainWindow", "Predecir"))
        self.btnRankingUser.setText(_translate("MainWindow", "Ranking"))
        self.label_2.setText(_translate("MainWindow", "Introduzca la pelicula"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUser), _translate("MainWindow", "Recomendador Usuario"))
        self.label.setText(_translate("MainWindow", "Introduzca la pelicula"))
        self.btnInformation.setText(_translate("MainWindow", "Informacion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInformacion), _translate("MainWindow", "Informacion"))

    def btnRanking_clicked(self):
        try: 
            film = self.txtEditGeneral.toPlainText()
            ranking = rg.genre_recommendations(film, rg.cosine_sim_df, rg.movies[['title', 'genres']])
            self.plainTxtGeneral.setPlainText(str(ranking))
            self.lblErrorGeneral.setText("")
        except:
            self.lblErrorGeneral.setText("Pelicula no encontrada")

    def btnPredict_clicked(self):
        try:
            film = self.txtEditUser.toPlainText()
            rating = pu.predecir_puntuacion(film)
            self.plainTxtUser.setPlainText(str(rating))
            self.lblErrorUser.setText("")
        except:
            self.lblErrorUser.setText("Pelicula no encontrada")


    def btnRankingUser_clicked(self):
        try:
            self.plainTxtUser.setPlainText(str(pu.RecomendacionDadoUsuario()))
            self.lblErrorUser.setText("")
        except:
            self.lblErrorUser.setText("Usuario no encontrado")

    
    def btnInformation_clicked(self):
        try:
            film = self.txtEditInfo.toPlainText()
            sinopsis = ws.get_sinopsis(film)
            self.plainTxtInfo.setPlainText(str(sinopsis))
            genre = ws.df_movies[ws.df_movies["title"]== film]
            self.lblGenres.setText(str(genre["genres"]))
            self.lblErrorInfo.setText("")
        except:
            self.lblErrorInfo.setText("Pelicula no encontrada")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
