# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_SSII.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import PelisSimilares as ps
import Objetivo2_final as o2
import Recomendador as recom
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.tabWidget.setObjectName("tabWidget")

        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.plainTxtGeneral = QtWidgets.QPlainTextEdit(self.tabGeneral)
        self.plainTxtGeneral.setGeometry(QtCore.QRect(10, 80, 771, 391))
        self.plainTxtGeneral.setObjectName("plainTxtGeneral")
        self.plainTxtGeneral.setReadOnly(True)
        self.txtEditGeneral = QtWidgets.QTextEdit(self.tabGeneral)
        self.txtEditGeneral.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.txtEditGeneral.setObjectName("txtEditGeneral")
        self.btnRanking = QtWidgets.QPushButton(self.tabGeneral)
        self.btnRanking.setGeometry(QtCore.QRect(710, 520, 75, 23))
        self.btnRanking.setObjectName("btnRanking")
        self.btnRanking.clicked.connect(self.btnRanking_clicked)
        self.label_3 = QtWidgets.QLabel(self.tabGeneral)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tabGeneral, "")

        self.tabUser = QtWidgets.QWidget()
        self.tabUser.setObjectName("tabUser")
        self.txtEditUser = QtWidgets.QTextEdit(self.tabUser)
        self.txtEditUser.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.txtEditUser.setObjectName("txtEditUser")
        self.plainTxtUser = QtWidgets.QPlainTextEdit(self.tabUser)
        self.plainTxtUser.setGeometry(QtCore.QRect(10, 80, 771, 391))
        self.plainTxtUser.setObjectName("plainTxtUser")
        self.plainTxtUser.setReadOnly(True)
        self.btnPredict = QtWidgets.QPushButton(self.tabUser)
        self.btnPredict.setGeometry(QtCore.QRect(710, 520, 75, 23))
        self.btnPredict.setObjectName("btnPredict")
        self.btnPredict.clicked.connect(self.btnPredict_clicked)
        self.btnRankingUser = QtWidgets.QPushButton(self.tabUser)
        self.btnRankingUser.setGeometry(QtCore.QRect(620, 520, 75, 23))
        self.btnRankingUser.setObjectName("btnRankingUser")
        self.btnRankingUser.clicked.connect(self.btnRankingUser_clicked)
        self.label_2 = QtWidgets.QLabel(self.tabUser)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tabUser, "")

        self.tabInformacion = QtWidgets.QWidget()
        self.tabInformacion.setObjectName("tabInformacion")
        self.plainTxtInfo = QtWidgets.QPlainTextEdit(self.tabInformacion)
        self.plainTxtInfo.setGeometry(QtCore.QRect(10, 150, 771, 321))
        self.plainTxtInfo.setObjectName("plainTxtInfo")
        self.txtEditInfo = QtWidgets.QTextEdit(self.tabInformacion)
        self.txtEditInfo.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.txtEditInfo.setObjectName("txtEditInfo")
        self.label = QtWidgets.QLabel(self.tabInformacion)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lblGenres = QtWidgets.QLabel(self.tabInformacion)
        self.lblGenres.setGeometry(QtCore.QRect(0, 80, 771, 41))
        self.lblGenres.setText("")
        self.lblGenres.setObjectName("lblGenres")
        self.btnInformation = QtWidgets.QPushButton(self.tabInformacion)
        self.btnInformation.setGeometry(QtCore.QRect(710, 530, 75, 23))
        self.btnInformation.setObjectName("btnInformation")
        self.btnInformation.clicked.connect(self.btnInformation_clicked)
        self.tabWidget.addTab(self.tabInformacion, "")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistemas Inteligentes"))
        self.btnRanking.setText(_translate("MainWindow", "Ranking"))
        self.label_3.setText(_translate("MainWindow", "Introduzca la pelicula"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("MainWindow", "Recomendador General"))
        self.btnPredict.setText(_translate("MainWindow", "Predecir"))
        self.btnRankingUser.setText(_translate("MainWindow", "Ranking"))
        self.label_2.setText(_translate("MainWindow", "Introduzca la pelicula"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUser), _translate("MainWindow", "Recomendador Usuario"))
        self.label.setText(_translate("MainWindow", "Introduzca la pelicula"))
        self.btnInformation.setText(_translate("MainWindow", "Informacion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInformacion), _translate("MainWindow", "Informacion"))

    def btnRanking_clicked(self):
        film = self.txtEditGeneral.toPlainText()
        ranking = ps.genre_recommendations(film, ps.cosine_sim_df, ps.movies[['title', 'genres']])
        self.plainTxtGeneral.setPlainText(str(ranking))

    def btnPredict_clicked(self):
        film = self.txtEditUser.toPlainText()
        rating = o2.predecir_puntuacion(film)
        self.plainTxtUser.setPlainText(str(rating))

    def btnRankingUser_clicked(self):
        self.plainTxtUser.setPlainText(str(o2.RecomendacionDadoUsuario()))
    
    def btnInformation_clicked(self):
        film = self.txtEditUser.toPlainText()
        print(recom.get_sinopsis(film))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
